name: flutter_chat_test_with_use_desk
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  file_picker: ^5.0.1
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.4
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  camera: 0.10.0+1
  usedesk: 
    path: ./../usedesk_package
  uuid: ^3.0.6
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
dev_dependencies:
  build_runner: 2.0.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/assets/
    - assets/